/*
 * NSX Manager API
 *
 * VMware NSX Manager REST API
 *
 * API version: 4.1.0.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package containerinventory

import "github.com/vmware/go-vmware-nsxt/common"

// A Gateway describes how traffic can be translated to Services within the container cluster.
type ContainerGateway struct {
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []common.ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string                   `json:"_schema,omitempty"`
	Self   *common.SelfResourceLink `json:"_self,omitempty"`
	// Timestamp of last modification
	LastSyncTime int64 `json:"_last_sync_time,omitempty"`
	// Description of this resource
	Description string `json:"description,omitempty"`
	// Defaults to ID if not set
	DisplayName string `json:"display_name,omitempty"`
	// The type of this resource.
	ResourceType string `json:"resource_type"`
	// Specifies list of scope of discovered resource. e.g. if VHC path is associated with principal identity, who owns the discovered resource, then scope id will be VHC path and scope type will be VHC.
	Scope []DiscoveredResourceScope `json:"scope,omitempty"`
	// Opaque identifiers meaningful to the API user
	Tags []common.Tag `json:"tags,omitempty"`
	// Specifies addresses which lists the IP addresses that have actually been bound to the gateway.
	Addresses []ContainerGatewayAddress `json:"addresses,omitempty"`
	// Specifies identifier of the container cluster of this container gateway.
	ContainerClusterId string `json:"container_cluster_id,omitempty"`
	// Specifies identifier of the container project of this container gateway.
	ContainerProjectId string `json:"container_project_id,omitempty"`
	// Specifies identifier of the container gateway.
	ExternalId string `json:"external_id"`
	// Specifies list of listeners which defines logical endpoints that are bound on this Gateway's addresses.
	Listeners []ContainerGatewayListener `json:"listeners,omitempty"`
	// Array of additional specific properties of container ip pool in key-value format.
	OriginProperties []common.KeyValuePair `json:"origin_properties,omitempty"`
	// Specifies container gateway specification.
	Spec string `json:"spec,omitempty"`
}
