/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Aggregate of DNS forwarder statistics across enforcement points. 
type AggregateDnsForwarderStatistics struct {
	// String path of the DNS forwarder intent. 
	IntentPath string `json:"intent_path"`
	// List of DNS forwarder statistics per enforcement point. 
	StatisticsPerEnforcementPoint []DnsForwarderStatisticsPerEnforcementPoint `json:"statistics_per_enforcement_point,omitempty"`
}
