/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer DnsAttacks object
type AlbDnsAttacks struct {
	// Mode of dealing with the attacks - perform detection only, or detect and mitigate the attacks. 
	Attacks []AlbDnsAttack `json:"attacks,omitempty"`
	// Mode of dealing with the attacks - perform detection only, or detect and mitigate the attacks. Enum options - DETECTION, MITIGATION. 
	OperMode string `json:"oper_mode,omitempty"`
}
