/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Intrusions that are detected, grouped by signature. It contains the signature id, severity, name, the number of intrusions of that type and the first occurence. 
type PolicyIdsEventsBySignature struct {
	// Number of times this particular signature was detected.
	Count int64 `json:"count,omitempty"`
	// First occurence of the intrusion, in epoch milliseconds.
	FirstOccurence int64 `json:"first_occurence,omitempty"`
	// Flag indicating an ongoing intrusion.
	IsOngoing bool `json:"is_ongoing,omitempty"`
	// IDSEvent resource type.
	ResourceType string `json:"resource_type,omitempty"`
	// Severity of the threat covered by the signature, can be Critical, High, Medium, or Low.
	Severity string `json:"severity,omitempty"`
	// Signature ID pertaining to the detected intrusion.
	SignatureId int64 `json:"signature_id,omitempty"`
	// Name of the signature pertaining to the detected intrusion.
	SignatureName string `json:"signature_name,omitempty"`
	// The source where the intrusion was detected. Possible values are GATEWAY and HOST.
	TrafficType string `json:"traffic_type,omitempty"`
}
