/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type IpAddresses struct {
	// The IP addresses in the form of IP Address, IP Range, CIDR, used as source IPs or destination IPs of filters.
	IpAddresses []string `json:"ip_addresses,omitempty"`
}
