/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// This holds the request parameters required to invoke export task. 
type ExportRequestParameter struct {
	// Policy path of a draft which is to be exported. If not provided, current firewall configuration will then be exported. 
	DraftPath string `json:"draft_path,omitempty"`
	// Passphrase to sign exported files. The passphrase specified must be at least 8 characters in length and must contain at least one lowercase, one uppercase, one numeric character and one non-space special character. 
	Passphrase string `json:"passphrase,omitempty"`
}
