/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Deployment version with chart name 
type DeploymentVersionSpec struct {
	// Deployment chart name.
	ChartName string `json:"chart_name,omitempty"`
	// List of deployment versions.
	Versions string `json:"versions,omitempty"`
}
