/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// ID and status of the Identity Firewall enabled Compute collection's transport node. 
type IdfwTransportNodeStatus struct {
	// TransportNode ID of the Identity Firewall enabled Compute collection's transport node. 
	TransportNodeId string `json:"transport_node_id"`
	// Status of the IDFW transport node.
	TransportNodeStatus []IdfwTransportNodeCondition `json:"transport_node_status"`
}
