/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// L2VPN tunnel encapsulation config.
type L2VpnTunnelEncapsulation struct {
	// IP Address of the local tunnel port. This property only applies in CLIENT mode. 
	LocalEndpointAddress string `json:"local_endpoint_address,omitempty"`
	// IP Address of the peer tunnel port. This property only applies in CLIENT mode. 
	PeerEndpointAddress string `json:"peer_endpoint_address,omitempty"`
	// Encapsulation protocol used by the tunnel.
	Protocol string `json:"protocol,omitempty"`
}
