/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Enable address_families and route filtering in each direction
type BgpRouteFiltering struct {
	// Address family type. If not configured, this property automatically derived for IPv4 & IPv6 peer configuration.
	AddressFamily string `json:"address_family,omitempty"`
	// Flag to enable address family.
	Enabled bool `json:"enabled,omitempty"`
	// Specify path of prefix-list or route map to filter routes for IN direction. 
	InRouteFilters []string `json:"in_route_filters,omitempty"`
	// Maximum number of routes for the address family. 
	MaximumRoutes int32 `json:"maximum_routes,omitempty"`
	// Specify path of prefix-list or route map to filter routes for OUT direction. When not specified, a built-in prefix-list named 'prefixlist-out-default' is automatically applied. 
	OutRouteFilters []string `json:"out_route_filters,omitempty"`
}
