/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type AgentStatusCount struct {
	// List of agent statuses belonging to the transport node
	Agents []AgentStatus `json:"agents,omitempty"`
	// Down count
	DownCount int32 `json:"down_count,omitempty"`
	// Roll-up agent status
	Status string `json:"status,omitempty"`
	// Up count
	UpCount int32 `json:"up_count,omitempty"`
}
