/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// This object holds auto assigned route distinguishers for Layer 2 and Layer 3 configurations.
type AutoRds struct {
	// List of layer 2 Auto assigned Route Distinguisher
	L2AutoRds []L2AutoRd `json:"l2_auto_rds,omitempty"`
	// This field is auto assigned by the system. The auto RD seed is populated when user does not assign a route_distinguisher field in the gateway. 
	L3AutoRd string `json:"l3_auto_rd,omitempty"`
}
