/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// IPSec VPN session statistics represents statistics on an NSX-T type of enforcement point. It gives aggregated statistics of all policies for all the tunnels. 
type IpSecVpnSessionStatisticsNsxT struct {
	Alarm *PolicyRuntimeAlarm `json:"alarm,omitempty"`
	// Policy Path referencing the enforcement point where the info is fetched. 
	EnforcementPointPath string `json:"enforcement_point_path,omitempty"`
	ResourceType string `json:"resource_type"`
	AggregateTrafficCounters *IpSecVpnTrafficCounters `json:"aggregate_traffic_counters,omitempty"`
	// Display Name of vpn session.
	DisplayName string `json:"display_name,omitempty"`
	IkeStatus *IpSecVpnIkeSessionStatus `json:"ike_status,omitempty"`
	IkeTrafficStatistics *IpSecVpnIkeTrafficStatistics `json:"ike_traffic_statistics,omitempty"`
	// Timestamp when the data was last updated. 
	LastUpdateTimestamp int64 `json:"last_update_timestamp,omitempty"`
	// Gives aggregate traffic statistics across all ipsec tunnels and individual tunnel statistics. 
	PolicyStatistics []IpSecVpnPolicyTrafficStatistics `json:"policy_statistics,omitempty"`
}
