/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// IPSecVPN site specific attributes specified only on GM. This allows user to specify site specific parameters which overrides the correspondig attributes in the IPSecVpnSession Object.
type SiteOverride struct {
	// Policy path referencing Local endpoint.
	LocalEndpointPath string `json:"local_endpoint_path"`
	// Policy path referencing LocateService where SiteOverride attributes will be applied
	LocaleServicePath string `json:"locale_service_path"`
	// Public IPV4 address of the remote device terminating the VPN connection.
	PeerAddress string `json:"peer_address"`
	// Peer ID to uniquely identify the peer site. The peer ID is the public IP address of the remote device terminating the VPN tunnel. When NAT is configured for the peer, enter the private IP address of the peer.
	PeerId string `json:"peer_id"`
	// IP Tunnel interfaces. This property is mandatory for RouteBasedIpSecVpn session.
	TunnelInterfaces []IpSecVpnTunnelInterface `json:"tunnel_interfaces,omitempty"`
}
