/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Detailed information about static address for the port.
type PortAddressBindingEntry struct {
	// IP Address for port binding
	IpAddress string `json:"ip_address,omitempty"`
	// Mac address for port binding
	MacAddress string `json:"mac_address,omitempty"`
	// VLAN ID for port binding
	VlanId int64 `json:"vlan_id,omitempty"`
}
