/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer URIParamQuery object
type AlburiParamQuery struct {
	// Concatenate a string to the query of the incoming request URI and then use it in the request URI going to the backend server. 
	AddString string `json:"add_string,omitempty"`
	// Use or drop the query of the incoming request URI in the request URI to the backend server. Default value when not specified in API or module is interpreted by ALB Controller as true. 
	KeepQuery bool `json:"keep_query,omitempty"`
}
