/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer CloneServer object
type AlbCloneServer struct {
	IpAddress *AlbIpAddr `json:"ip_address,omitempty"`
	// MAC Address of the Clone Server.
	Mac string `json:"mac,omitempty"`
	// Network to clone the traffic to. It is a reference to an object of type Network. 
	NetworkName string `json:"network_name,omitempty"`
	Subnet *AlbIpAddrPrefix `json:"subnet,omitempty"`
}
