/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type InterfaceArpProxyCsvEntry struct {
	// ARP proxy information for a service with ip.
	ArpProxyIp string `json:"arp_proxy_ip,omitempty"`
	// Policy path of gateway interface
	InterfacePath string `json:"interface_path,omitempty"`
	// Identifier of connected service on port.
	ServiceId string `json:"service_id,omitempty"`
}
