/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer VSDataScripts object
type AlbvsDataScripts struct {
	// Index of the virtual service datascript collection.
	Index int64 `json:"index"`
	// path of the virtual service datascript collection. It is a reference to an object of type VSDataScriptSet. 
	VsDatascriptSetPath string `json:"vs_datascript_set_path"`
}
