/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Deployment progress state of Advanced Load Balancer controller VM. This Object contains name of current deployment step and overall progress percentage.
type AlbControllerNodeVmDeploymentProgressState struct {
	// Name of the current running step of deployment
	CurrentStepTitle string `json:"current_step_title,omitempty"`
	// Overall progress percentage of deployment completed
	Progress int64 `json:"progress,omitempty"`
}
