/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer HSMThalesNetHsm object
type AlbhsmThalesNetHsm struct {
	// Electronic serial number of the netHSM device. Use Thales anonkneti utility to find the netHSM ESN. 
	Esn string `json:"esn"`
	// Hash of the key that netHSM device uses to authenticate itself. Use Thales anonkneti utility to find the netHSM keyhash. 
	Keyhash string `json:"keyhash"`
	// Local module id of the netHSM device. Default value when not specified in API or module is interpreted by ALB Controller as 0. 
	ModuleId int64 `json:"module_id,omitempty"`
	// Priority class of the nethsm in an high availability setup. 1 is the highest priority and 100 is the lowest priority. Allowed values are 1-100. Default value when not specified in API or module is interpreted by ALB Controller as 100. 
	Priority int64 `json:"priority"`
	RemoteIp *AlbIpAddr `json:"remote_ip"`
	// Port at which the netHSM device accepts the connection. Allowed values are 1-65535. Default value when not specified in API or module is interpreted by ALB Controller as 9004. 
	RemotePort int64 `json:"remote_port,omitempty"`
}
