/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Past backup operation details
type BackupOperationHistory struct {
	// Statuses of previous cluser backups
	ClusterBackupStatuses []BackupOperationStatus `json:"cluster_backup_statuses,omitempty"`
	// Statuses of previous inventory backups
	InventoryBackupStatuses []BackupOperationStatus `json:"inventory_backup_statuses,omitempty"`
	// Statuses of previous node backups
	NodeBackupStatuses []BackupOperationStatus `json:"node_backup_statuses,omitempty"`
}
