/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer IPNetworkSubnet object
type AlbipNetworkSubnet struct {
	// Network for VirtualService IP allocation with Vantage as the IPAM provider. Network should be created before this is configured. It is a reference to an object of type Network. 
	NetworkName string `json:"network_name,omitempty"`
	Subnet *AlbIpAddrPrefix `json:"subnet,omitempty"`
	Subnet6 *AlbIpAddrPrefix `json:"subnet6,omitempty"`
	// Subnet UUID or Name or Prefix for VirtualService IPv6 allocation with AWS or OpenStack as the IPAM provider. Only one of subnet or subnet_uuid configuration is allowed. Allowed in Basic edition, Essentials edition, Enterprise edition. 
	Subnet6Uuid string `json:"subnet6_uuid,omitempty"`
	// Subnet UUID or Name or Prefix for VirtualService IP allocation with AWS or OpenStack as the IPAM provider. Only one of subnet or subnet_uuid configuration is allowed. 
	SubnetUuid string `json:"subnet_uuid,omitempty"`
}
