/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Security Feature feature entity
type SecurityFeatureBase struct {
	// true - enable the feature, false - disable the feture
	Enable bool `json:"enable"`
}
