/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type PolicyEdgeClusterMemberInterSiteStatus struct {
	EdgeNodePath *ResourceReference `json:"edge_node_path,omitempty"`
	// Total number of current established inter-site IBGP sessions.
	EstablishedBgpSessions int64 `json:"established_bgp_sessions,omitempty"`
	// Inter-site BGP neighbor status.
	NeighborStatus []PolicyBgpNeighborStatus `json:"neighbor_status,omitempty"`
	// Edge node IBGP status
	Status string `json:"status,omitempty"`
	// Total number of inter-site IBGP sessions.
	TotalBgpSessions int64 `json:"total_bgp_sessions,omitempty"`
}
