/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer AutoScaleOpenStackSettings object
type AlbAutoScaleOpenStackSettings struct {
	// Avi Controller will use this URL to scale downthe pool. Cloud connector will automatically update the membership. This is an alpha feature. 
	HeatScaleDownUrl string `json:"heat_scale_down_url,omitempty"`
	// Avi Controller will use this URL to scale upthe pool. Cloud connector will automatically update the membership. This is an alpha feature. 
	HeatScaleUpUrl string `json:"heat_scale_up_url,omitempty"`
}
