/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type FirstNSampling struct {
	// Sampling type
	SamplingType string `json:"sampling_type"`
	// Number of packets to be sampled
	MatchNumber int64 `json:"match_number"`
}
