/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Tag operation status for particular resource type and resource ids. 
type ResourceTypeTagStatus struct {
	// List of resources on which tag needs to be applied. 
	ResourceTagStatus []ResourceTagStatus `json:"resource_tag_status,omitempty"`
	// Resource type
	ResourceType string `json:"resource_type"`
}
