/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Patch Resources is an action to create/patch resources in response to an event. 
type PatchResources struct {
	// Reaction Action resource type. 
	ResourceType string `json:"resource_type"`
	// Patch body representing a Hierarchical Patch payload. The resources included in the body are patched replacing the injections' keys with their actual values. 
	Body interface{} `json:"body"`
	// Injections holding keys (variables) and their corresponding values.
	Injections []Injection `json:"injections,omitempty"`
}
