/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// IPSec VPN tunnel traffic statistics.
type IpSecVpnTunnelTrafficStatistics struct {
	// Total number of incoming bytes on inbound Security association. 
	BytesIn int64 `json:"bytes_in,omitempty"`
	// Total number of outgoing bytes on outbound Security association. 
	BytesOut int64 `json:"bytes_out,omitempty"`
	// Total number of packets dropped due to decryption failures. 
	DecryptionFailures int64 `json:"decryption_failures,omitempty"`
	// Total number of incoming packets dropped on inbound security association. 
	DroppedPacketsIn int64 `json:"dropped_packets_in,omitempty"`
	// Total number of outgoing packets dropped on outbound security association. 
	DroppedPacketsOut int64 `json:"dropped_packets_out,omitempty"`
	// Total number of packets dropped because of failure in encryption. 
	EncryptionFailures int64 `json:"encryption_failures,omitempty"`
	// Total number of packets dropped due to integrity failures. 
	IntegrityFailures int64 `json:"integrity_failures,omitempty"`
	// Tunnel local subnet in IPv4 CIDR Block format. 
	LocalSubnet string `json:"local_subnet,omitempty"`
	// Number of packets dropped because of no matching policy is available. 
	NomatchingPolicyErrors int64 `json:"nomatching_policy_errors,omitempty"`
	// Total number of incoming packets on inbound Security association. 
	PacketsIn int64 `json:"packets_in,omitempty"`
	// Total number of outgoing packets on outbound Security association. 
	PacketsOut int64 `json:"packets_out,omitempty"`
	// Total number of incoming packets dropped on inbound Security association. 
	PacketsReceivedOtherError int64 `json:"packets_received_other_error,omitempty"`
	// Total number of packets dropped while sending for any reason. 
	PacketsSentOtherError int64 `json:"packets_sent_other_error,omitempty"`
	// Tunnel peer subnet in IPv4 CIDR Block format. 
	PeerSubnet string `json:"peer_subnet,omitempty"`
	// Policy UUID of IPSec Tunnel.
	PolicyId string `json:"policy_id,omitempty"`
	// Total number of packets dropped due to replay check on that Security association. 
	ReplayErrors int64 `json:"replay_errors,omitempty"`
	// Totoal number of security association mismatch errors on incoming packets. 
	SaMismatchErrorsIn int64 `json:"sa_mismatch_errors_in,omitempty"`
	// Totoal number of security association mismatch errors on outgoing packets. 
	SaMismatchErrorsOut int64 `json:"sa_mismatch_errors_out,omitempty"`
	// Total number of packets dropped while sending due to overflow in sequence number. 
	SeqNumberOverflowError int64 `json:"seq_number_overflow_error,omitempty"`
	// Gives the detailed reason about the tunnel when it is down. If tunnel is UP tunnel down reason will be empty. 
	TunnelDownReason string `json:"tunnel_down_reason,omitempty"`
	// Specifies the status of tunnel, if it is UP/DOWN. 
	TunnelStatus string `json:"tunnel_status,omitempty"`
}
