/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer IpAddr object
type AlbIpAddr struct {
	// IP address.
	Addr string `json:"addr"`
	// Enum options - V4, DNS, V6.
	Type_ string `json:"type"`
}
