/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Multicast Forwarding Per Edge. 
type MulticastForwardingPerEdge struct {
	// Policy path to edge node. 
	EdgePath string `json:"edge_path"`
	McastForwarding []MulticastForwarding `json:"mcast_forwarding,omitempty"`
}
