/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// List of same type members to either add or remove from a group.
type GroupMemberList struct {
	// This array contains group members of similar types.
	Members []string `json:"members"`
}
