/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type LbServiceInstanceDetailPerStatus struct {
	// The detailed information of the load balancer instance. This field will be only returned on realtime status API. 
	InstanceDetails []LbServiceInstanceDetail `json:"instance_details,omitempty"`
	// It means the total number of instances in this status type for the given transport node. 
	InstanceNumber int64 `json:"instance_number,omitempty"`
	// The type of load balancer instance status. 
	Status string `json:"status,omitempty"`
}
