/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type TunnelSubnet struct {
	// Subnet ip addresses
	IpAddresses []string `json:"ip_addresses"`
	// Subnet Prefix Length
	PrefixLength int64 `json:"prefix_length"`
}
