/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// The load balancer node usage summary for all nodes from specific enforcement point. Only edge node is supported. The summary contains all edge nodes which are configured in edge clusters. 
type LbNodeUsageSummary struct {
	Alarm *PolicyRuntimeAlarm `json:"alarm,omitempty"`
	// Policy Path referencing the enforcement point where the info is fetched. 
	EnforcementPointPath string `json:"enforcement_point_path,omitempty"`
	// Current load balancer credits in use for all nodes. For example, configuring a medium load balancer on a node consumes 10 credits. If there are 2 medium instances configured, the current load balancer credit number is 2 * 10 = 20. 
	CurrentLoadBalancerCredits int64 `json:"current_load_balancer_credits,omitempty"`
	// The overall count of pool members configured on all nodes. 
	CurrentPoolMemberCount int64 `json:"current_pool_member_count,omitempty"`
	// The load balancer credit capacity means the maximum credits which can be used for load balancer service configuration for all nodes. 
	LoadBalancerCreditCapacity int64 `json:"load_balancer_credit_capacity,omitempty"`
	// The property identifies array of node count for each severity. 
	NodeCounts []LbNodeCountPerSeverity `json:"node_counts,omitempty"`
	// The property identifies all LB node usages. By default, it is not included in response. It exists when parameter ?include_usages=true. 
	NodeUsages []LbNodeUsage `json:"node_usages,omitempty"`
	// Pool member capacity means maximum number of pool members which can be configured on all nodes. 
	PoolMemberCapacity int64 `json:"pool_member_capacity,omitempty"`
	// The severity calculation is based on overall credit usage percentage of load balancer for all nodes. 
	Severity string `json:"severity,omitempty"`
	// The overall usage percentage of all nodes for load balancer. The value is the larger value between overall pool member usage percentage and overall load balancer credit usage percentage. 
	UsagePercentage float32 `json:"usage_percentage,omitempty"`
}
