/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type OspfDatabaseStatus struct {
	// OSPF area id to filter the the OSPF database.
	AreaId string `json:"area_id,omitempty"`
	// array of ASBR summary link state of OSPF database
	AsbrSummaryLinkStates []MpOspfSummaryLinkStates `json:"asbr_summary_link_states,omitempty"`
	// Policy path to edge node. 
	EdgePath string `json:"edge_path,omitempty"`
	// array of external link of OSPF database
	ExternalLinkStates []MpOspfExternalLinkState `json:"external_link_states,omitempty"`
	// array of network link state of OSPF database
	NetLinkStates []MpOspfNetworkLinkStates `json:"net_link_states,omitempty"`
	// array of nssa external link of OSPF database
	NssaExternalLinkStates []MpOspfExternalLinkState `json:"nssa_external_link_states,omitempty"`
	// array of link state of OSPF database
	RouterLinkStates []MpOspfRouterLinkStates `json:"router_link_states,omitempty"`
	// array of summary link state of OSPF database
	SummaryLinkStates []MpOspfSummaryLinkStates `json:"summary_link_states,omitempty"`
}
