/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Antrea agents information
type AntreaAgentsInfo struct {
	// The number of degraded agents
	DegradedAgentNum int32 `json:"degraded_agent_num,omitempty"`
	// The number of failed agents
	FailedAgentNum int32 `json:"failed_agent_num,omitempty"`
	// The number of healthy agents
	HealthyAgentNum int32 `json:"healthy_agent_num,omitempty"`
}
