/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Feature Permission
type FeaturePermission struct {
	// Feature Id
	Feature string `json:"feature"`
	// Feature Description
	FeatureDescription string `json:"feature_description,omitempty"`
	// Feature Name
	FeatureName string `json:"feature_name,omitempty"`
	// Is execute recommended
	IsExecuteRecommended bool `json:"is_execute_recommended,omitempty"`
	// Is internal
	IsInternal bool `json:"is_internal,omitempty"`
	// Permission
	Permission string `json:"permission"`
}
