/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer DiscoveredNetwork object
type AlbDiscoveredNetwork struct {
	// Discovered network for this IP. It is a reference to an object of type Network. 
	NetworkName string `json:"network_name"`
	// Discovered subnet for this IP.
	Subnet []AlbIpAddrPrefix `json:"subnet,omitempty"`
	// Discovered IPv6 subnet for this IP.
	Subnet6 []AlbIpAddrPrefix `json:"subnet6,omitempty"`
}
