/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer DnsRuleMatchTarget object
type AlbDnsRuleMatchTarget struct {
	ClientIpAddress *AlbDnsClientIpMatch `json:"client_ip_address,omitempty"`
	GeoLocation *AlbDnsGeoLocationMatch `json:"geo_location,omitempty"`
	Protocol *AlbDnsTransportProtocolMatch `json:"protocol,omitempty"`
	QueryName *AlbDnsQueryNameMatch `json:"query_name,omitempty"`
	QueryType *AlbDnsQueryTypeMatch `json:"query_type,omitempty"`
}
