/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type SubjectPublicKeyHash struct {
	// List of SHA256 hashes of the Public Key of the revoked certificates with the specified subject.
	PublicKeySha256Hashes []string `json:"public_key_sha256_hashes,omitempty"`
	// Subject Distinguished Name of the revoked certificates.
	Subject string `json:"subject,omitempty"`
}
