/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Domain synchronization settings
type DirectoryDomainSyncSettings struct {
	// Directory domain delta synchronization interval time between two delta sync in minutes.
	DeltaSyncInterval int64 `json:"delta_sync_interval,omitempty"`
	// Directory domain full synchronization schedule using cron expression. For example, cron expression \"0 0 12 ? * SUN *\" means full sync is scheduled every Sunday midnight. If this object is null, it means there is no background cron job running for full sync.
	FullSyncCronExpr string `json:"full_sync_cron_expr,omitempty"`
	// Sync delay after Directory domain has been successfully created. if delay is -1, initial full sync will not be triggered. 
	SyncDelayInSec int32 `json:"sync_delay_in_sec,omitempty"`
}
