/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Consolidated Realized Status of an intent object across enforcement points. 
type ConsolidatedRealizedStatus struct {
	// Intent path of object, forward slashes must be escaped using %2F. 
	IntentPath string `json:"intent_path,omitempty"`
	ConsolidatedStatus *ConsolidatedStatus `json:"consolidated_status,omitempty"`
	// List of Consolidated Realized Status per enforcement point.
	ConsolidatedStatusPerEnforcementPoint []ConsolidatedStatusPerEnforcementPoint `json:"consolidated_status_per_enforcement_point,omitempty"`
	// Represent highest intent version across all realized objects
	IntentVersion string `json:"intent_version,omitempty"`
	// Aggregated Realization state of this object
	PublishStatus string `json:"publish_status"`
}
