/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Different form factor for deployment. 
type FormFactors struct {
	Advanced *FormFactorDetail `json:"advanced,omitempty"`
	Evaluation *FormFactorDetail `json:"evaluation,omitempty"`
	Standard *FormFactorDetail `json:"standard,omitempty"`
}
