/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Provides details of config flow in federation Federation has the following flows - Global Manager to Local Manager (GM -> LM) - Local Manager to Glocal Manager (LM -> GM) - Global Manager Active to Glocal Manager Standby (GM -> GM) - Local Manager to Local Manager (LM -> LM) 
type FlowInfo struct {
	CrossSiteFlowInfo *CrossSiteFlowInfo `json:"cross_site_flow_info,omitempty"`
	// Flow identifier
	FlowType string `json:"flow_type,omitempty"`
	// System identifier for the flow
	Id string `json:"id,omitempty"`
	// Every flow will have transmitter and receiver queues.
	QueueInfos []FederationQueueInfo `json:"queue_infos,omitempty"`
}
