/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer ServicePoolSelector object
type AlbServicePoolSelector struct {
	// It is a reference to an object of type PoolGroup.
	ServicePoolGroupPath string `json:"service_pool_group_path,omitempty"`
	// It is a reference to an object of type Pool.
	ServicePoolPath string `json:"service_pool_path,omitempty"`
	// Pool based destination port. Allowed values are 1-65535. 
	ServicePort int64 `json:"service_port"`
	// The end of the Service port number range. Allowed values are 1-65535. Special values are 0- 'single port'. Default value when not specified in API or module is interpreted by ALB Controller as 0. 
	ServicePortRangeEnd int64 `json:"service_port_range_end,omitempty"`
	// Destination protocol to match for the pool selection. If not specified, it will match any protocol. Enum options - PROTOCOL_TYPE_TCP_PROXY, PROTOCOL_TYPE_TCP_FAST_PATH, PROTOCOL_TYPE_UDP_FAST_PATH, PROTOCOL_TYPE_UDP_PROXY. 
	ServiceProtocol string `json:"service_protocol,omitempty"`
}
