/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Different NSX Application Platform deployment versions.
type DeploymentVersions struct {
	// List of deployment versions.
	Versions []DeploymentVersionSpec `json:"versions,omitempty"`
}
