/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer QueryMatch object
type AlbQueryMatch struct {
	// Case sensitivity to use for the match. Enum options - SENSITIVE, INSENSITIVE. Default value when not specified in API or module is interpreted by ALB Controller as INSENSITIVE. 
	MatchCase string `json:"match_case,omitempty"`
	// Criterion to use for matching the query in HTTP request URI. Enum options - QUERY_MATCH_CONTAINS. 
	MatchCriteria string `json:"match_criteria"`
	// String value(s).
	MatchStr []string `json:"match_str,omitempty"`
	// path of the string group(s). It is a reference to an object of type StringGroup. 
	StringGroupPaths []string `json:"string_group_paths,omitempty"`
}
