/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Status of the Identity Firewall compute collection's VM.
type IdfwVirtualMachineCondition struct {
	// VM IDFW Status.
	Status string `json:"status"`
	// IDFW compute collection's VM condition.
	StatusDetail string `json:"status_detail,omitempty"`
}
