/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Used to specify the local/peer subnets in IPSec VPN rule.
type IpSecVpnSubnet struct {
	// Subnet used in policy rule.
	Subnet string `json:"subnet"`
}
