/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Duplicate address binding information
type DuplicateAddressBindingEntry struct {
	Binding *PacketAddressClassifier `json:"binding,omitempty"`
	// Timestamp at which the binding was discovered via snooping or manually specified by the user 
	BindingTimestamp int64 `json:"binding_timestamp,omitempty"`
	// Source from which the address binding entry was obtained
	Source string `json:"source,omitempty"`
	// Provides the ID of the port on which the same address bidning exists 
	ConflictingPort string `json:"conflicting_port,omitempty"`
}
