/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// L3Vpn Statistics Per Enforcement Point. 
type L3VpnStatisticsPerEnforcementPoint struct {
	// Policy Path referencing the enforcement point wehere the statistics are fetched. 
	EnforcementPointPath string `json:"enforcement_point_path,omitempty"`
	ResourceType string `json:"resource_type"`
}
