/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// It represents the resource information which could identify resource. 
type ResourceInfo struct {
	// It will represent resource identifiers. For example, policy objects will be represented with paths and virtual machine will be represented with external ids. 
	ResourceIds []string `json:"resource_ids"`
	// It will represent resource type on which tag bulk operation to be performed. Supported resource type is VirtualMachine. 
	ResourceType string `json:"resource_type"`
}
