/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer Pool object
type AlbPool struct {
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	Self *SelfResourceLink `json:"_self,omitempty"`
	// The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected.
	Revision int32 `json:"_revision,omitempty"`
	// Timestamp of resource creation
	CreateTime int64 `json:"_create_time,omitempty"`
	// ID of the user who created this resource
	CreateUser string `json:"_create_user,omitempty"`
	// Timestamp of last modification
	LastModifiedTime int64 `json:"_last_modified_time,omitempty"`
	// ID of the user who last modified this resource
	LastModifiedUser string `json:"_last_modified_user,omitempty"`
	// Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity. 
	Protection string `json:"_protection,omitempty"`
	// Indicates system owned resource
	SystemOwned bool `json:"_system_owned,omitempty"`
	// Description of this resource
	Description string `json:"description,omitempty"`
	// Defaults to ID if not set
	DisplayName string `json:"display_name,omitempty"`
	// Unique identifier of this resource
	Id string `json:"id,omitempty"`
	// The type of this resource.
	ResourceType string `json:"resource_type,omitempty"`
	// Opaque identifiers meaningful to the API user
	Tags []Tag `json:"tags,omitempty"`
	// Path of its parent
	ParentPath string `json:"parent_path,omitempty"`
	// Absolute path of this object
	Path string `json:"path,omitempty"`
	// This is a UUID generated by the system for realizing the entity object. In most cases this should be same as 'unique_id' of the entity. However, in some cases this can be different because of entities have migrated thier unique identifier to NSX Policy intent objects later in the timeline and did not use unique_id for realization. Realization id is helpful for users to debug data path to correlate the configuration with corresponding intent. 
	RealizationId string `json:"realization_id,omitempty"`
	// Path relative from its parent
	RelativePath string `json:"relative_path,omitempty"`
	// This is a UUID generated by the GM/LM to uniquely identify entites in a federated environment. For entities that are stretched across multiple sites, the same ID will be used on all the stretched sites. 
	UniqueId string `json:"unique_id,omitempty"`
	// subtree for this type within policy tree containing nested elements. 
	Children []ChildPolicyConfigResource `json:"children,omitempty"`
	// Intent objects are not directly deleted from the system when a delete is invoked on them. They are marked for deletion and only when all the realized entities for that intent object gets deleted, the intent object is deleted. Objects that are marked for deletion are not returned in GET call. One can use the search API to get these objects. 
	MarkedForDelete bool `json:"marked_for_delete,omitempty"`
	// Global intent objects cannot be modified by the user. However, certain global intent objects can be overridden locally by use of this property. In such cases, the overridden local values take precedence over the globally defined values for the properties. 
	Overridden bool `json:"overridden,omitempty"`
	AnalyticsPolicy *AlbPoolAnalyticsPolicy `json:"analytics_policy,omitempty"`
	// Specifies settings related to analytics. It is a reference to an object of type AnalyticsProfile. 
	AnalyticsProfilePath string `json:"analytics_profile_path,omitempty"`
	// Synchronize Cisco APIC EPG members with pool servers.
	ApicEpgName string `json:"apic_epg_name,omitempty"`
	// Persistence will ensure the same user sticks to the same server for a desired duration of time. It is a reference to an object of type ApplicationPersistenceProfile. 
	ApplicationPersistenceProfilePath string `json:"application_persistence_profile_path,omitempty"`
	// If configured then Avi will trigger orchestration of pool server creation and deletion. It is a reference to an object of type AutoScaleLaunchConfig. 
	AutoscaleLaunchConfigPath string `json:"autoscale_launch_config_path,omitempty"`
	// Network Ids for the launch configuration.
	AutoscaleNetworks []string `json:"autoscale_networks,omitempty"`
	// Reference to Server Autoscale Policy. It is a reference to an object of type ServerAutoScalePolicy. 
	AutoscalePolicyPath string `json:"autoscale_policy_path,omitempty"`
	// Inline estimation of capacity of servers. Allowed in Basic(Allowed values- false) edition, Essentials(Allowed values- false) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	CapacityEstimation bool `json:"capacity_estimation,omitempty"`
	// The maximum time-to-first-byte of a server. Allowed values are 1-5000. Special values are 0 - 'Automatic'. Unit is MILLISECONDS. Allowed in Basic(Allowed values- 0) edition, Essentials(Allowed values- 0) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as 0. 
	CapacityEstimationTtfbThresh int64 `json:"capacity_estimation_ttfb_thresh,omitempty"`
	// Checksum of cloud configuration for Pool. Internally set by cloud connector. 
	CloudConfigCksum string `json:"cloud_config_cksum,omitempty"`
	// It is a reference to an object of type Cloud.
	CloudName string `json:"cloud_name,omitempty"`
	ConnPoolProperties *AlbConnPoolProperties `json:"conn_pool_properties,omitempty"`
	// Duration for which new connections will be gradually ramped up to a server recently brought online. Useful for LB algorithms that are least connection based. Allowed values are 1-300. Special values are 0 - 'Immediate'. Unit is MIN. Allowed in Basic(Allowed values- 0) edition, Essentials(Allowed values- 0) edition, Enterprise edition. Special default for Basic edition is 0, Essentials edition is 0, Enterprise is 10. Default value when not specified in API or module is interpreted by ALB Controller as 0. 
	ConnectionRampDuration int64 `json:"connection_ramp_duration,omitempty"`
	// Creator name.
	CreatedBy string `json:"created_by,omitempty"`
	// Traffic sent to servers will use this destination server port unless overridden by the server's specific port attribute. The SSL checkbox enables Avi to server encryption. Allowed values are 1-65535. Default value when not specified in API or module is interpreted by ALB Controller as 80. 
	DefaultServerPort int64 `json:"default_server_port,omitempty"`
	// Indicates whether existing IPs are disabled(false) or deleted(true) on dns hostname refreshDetail -- On a dns refresh, some IPs set on pool may no longer be returned by the resolver. These IPs are deleted from the pool when this knob is set to true. They are disabled, if the knob is set to false. Allowed in Basic(Allowed values- true) edition, Essentials(Allowed values- true) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as true. 
	DeleteServerOnDnsRefresh bool `json:"delete_server_on_dns_refresh,omitempty"`
	// Comma separated list of domain names which will be used to verify the common names or subject alternative names presented by server certificates. It is performed only when common name check host_check_enabled is enabled. 
	DomainName []string `json:"domain_name,omitempty"`
	// Inherited config from VirtualService.
	EastWest bool `json:"east_west,omitempty"`
	// Enable HTTP/2 for traffic from VirtualService to all backend servers in this pool. Allowed in Basic(Allowed values- false) edition, Essentials(Allowed values- false) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	EnableHttp2 bool `json:"enable_http2,omitempty"`
	// Enable or disable the pool. Disabling will terminate all open connections and pause health monitors. Default value when not specified in API or module is interpreted by ALB Controller as true. 
	Enabled bool `json:"enabled,omitempty"`
	// Names of external auto-scale groups for pool servers. Currently available only for AWS and Azure. 
	ExternalAutoscaleGroups []string `json:"external_autoscale_groups,omitempty"`
	FailAction *AlbFailAction `json:"fail_action,omitempty"`
	// Periodicity of feedback for fewest tasks server selection algorithm. Allowed values are 1-300. Unit is SEC. Default value when not specified in API or module is interpreted by ALB Controller as 10. 
	FewestTasksFeedbackDelay int64 `json:"fewest_tasks_feedback_delay,omitempty"`
	// Used to gracefully disable a server. Virtual service waits for the specified time before terminating the existing connections  to the servers that are disabled. Allowed values are 1-7200. Special values are 0 - 'Immediate', -1 - 'Infinite'. Unit is MIN. Default value when not specified in API or module is interpreted by ALB Controller as 1. 
	GracefulDisableTimeout int64 `json:"graceful_disable_timeout,omitempty"`
	// A list of NSX Groups where the Servers for the Pool are created . 
	GroupPaths []string `json:"group_paths,omitempty"`
	// Indicates if the pool is a site-persistence pool. Allowed in Basic edition, Essentials edition, Enterprise edition. 
	GslbSpEnabled bool `json:"gslb_sp_enabled,omitempty"`
	// Verify server health by applying one or more health monitors. Active monitors generate synthetic traffic from each Service Engine and mark a server up or down based on the response. The Passive monitor listens only to client to server communication. It raises or lowers the ratio of traffic destined to a server based on successful responses. It is a reference to an object of type HealthMonitor. Maximum of 50 items allowed. 
	HealthMonitorPaths []string `json:"health_monitor_paths,omitempty"`
	// Enable common name check for server certificate. If enabled and no explicit domain name is specified, Avi will use the incoming host header to do the match. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	HostCheckEnabled bool `json:"host_check_enabled,omitempty"`
	// Ignore the server port in building the load balancing state.Applicable only for consistent hash load balancing algorithm or Disable Port translation (use_service_port) use cases. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	IgnoreServerPort bool `json:"ignore_server_port,omitempty"`
	// The Passive monitor will monitor client to server connections and requests and adjust traffic load to servers based on successful responses. This may alter the expected behavior of the LB method, such as Round Robin. Default value when not specified in API or module is interpreted by ALB Controller as true. 
	InlineHealthMonitor bool `json:"inline_health_monitor,omitempty"`
	// Use list of servers from Ip Address Group. It is a reference to an object of type IpAddrGroup. 
	IpaddrgroupPath string `json:"ipaddrgroup_path,omitempty"`
	// The load balancing algorithm will pick a server within the pool's list of available servers. Values LB_ALGORITHM_NEAREST_SERVER and LB_ALGORITHM_TOPOLOGY are only allowed for GSLB pool. Enum options - LB_ALGORITHM_LEAST_CONNECTIONS, LB_ALGORITHM_ROUND_ROBIN, LB_ALGORITHM_FASTEST_RESPONSE, LB_ALGORITHM_CONSISTENT_HASH, LB_ALGORITHM_LEAST_LOAD, LB_ALGORITHM_FEWEST_SERVERS, LB_ALGORITHM_RANDOM, LB_ALGORITHM_FEWEST_TASKS, LB_ALGORITHM_NEAREST_SERVER, LB_ALGORITHM_CORE_AFFINITY, LB_ALGORITHM_TOPOLOGY. Allowed in Basic(Allowed values- LB_ALGORITHM_LEAST_CONNECTIONS,LB_ALGORITHM_ROUND_ROBIN,LB_ALGORITHM_CONSISTENT_HASH) edition, Essentials(Allowed values- LB_ALGORITHM_LEAST_CONNECTIONS,LB_ALGORITHM_ROUND_ROBIN,LB_ALGORITHM_CONSISTENT_HASH) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as LB_ALGORITHM_LEAST_CONNECTIONS. 
	LbAlgorithm string `json:"lb_algorithm,omitempty"`
	// HTTP header name to be used for the hash key.
	LbAlgorithmConsistentHashHdr string `json:"lb_algorithm_consistent_hash_hdr,omitempty"`
	// Degree of non-affinity for core affinity based server selection. Allowed values are 1-65535. Allowed in Basic(Allowed values- 2) edition, Essentials(Allowed values- 2) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as 2. 
	LbAlgorithmCoreNonaffinity int64 `json:"lb_algorithm_core_nonaffinity,omitempty"`
	// Criteria used as a key for determining the hash between the client and  server. Enum options - LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS, LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS_AND_PORT, LB_ALGORITHM_CONSISTENT_HASH_URI, LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_HEADER, LB_ALGORITHM_CONSISTENT_HASH_CUSTOM_STRING, LB_ALGORITHM_CONSISTENT_HASH_CALLID. Allowed in Basic(Allowed values- LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS) edition, Essentials(Allowed values- LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as LB_ALGORITHM_CONSISTENT_HASH_SOURCE_IP_ADDRESS. 
	LbAlgorithmHash string `json:"lb_algorithm_hash,omitempty"`
	// Allow server lookup by name. Allowed in Basic(Allowed values- false) edition, Essentials(Allowed values- false) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	LookupServerByName bool `json:"lookup_server_by_name,omitempty"`
	// List of labels to be used for granular RBAC. Allowed in Basic edition, Essentials edition, Enterprise edition. 
	Markers []AlbRoleFilterMatchLabel `json:"markers,omitempty"`
	// The maximum number of concurrent connections allowed to each server within the pool. NOTE  applied value will be no less than the number of service engines that the pool is placed on. If set to 0, no limit is applied. Default value when not specified in API or module is interpreted by ALB Controller as 0. 
	MaxConcurrentConnectionsPerServer int64 `json:"max_concurrent_connections_per_server,omitempty"`
	MaxConnRatePerServer *AlbRateProfile `json:"max_conn_rate_per_server,omitempty"`
	// Minimum number of health monitors in UP state to mark server UP. Allowed in Basic edition, Essentials edition, Enterprise edition. 
	MinHealthMonitorsUp int64 `json:"min_health_monitors_up,omitempty"`
	// Minimum number of servers in UP state for marking the pool UP. 
	MinServersUp int64 `json:"min_servers_up,omitempty"`
	// (internal-use) Networks designated as containing servers for this pool. The servers may be further narrowed down by a filter. This field is used internally by Avi, not editable by the user. 
	Networks []AlbNetworkFilter `json:"networks,omitempty"`
	// Avi will validate the SSL certificate present by a server against the selected PKI Profile. It is a reference to an object of type PKIProfile. 
	PkiProfilePath string `json:"pki_profile_path,omitempty"`
	// Manually select the networks and subnets used to provide reachability to the pool's servers. Specify the Subnet using the following syntax  10-1-1-0/24. Use static routes in VRF configuration when pool servers are not directly connected but routable from the service engine. 
	PlacementNetworks []AlbPlacementNetwork `json:"placement_networks,omitempty"`
	// Minimum number of requests to be queued when pool is full. Allowed in Basic(Allowed values- 128) edition, Essentials(Allowed values- 128) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as 128. 
	RequestQueueDepth int64 `json:"request_queue_depth,omitempty"`
	// Enable request queue when pool is full. Allowed in Basic(Allowed values- false) edition, Essentials(Allowed values- false) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	RequestQueueEnabled bool `json:"request_queue_enabled,omitempty"`
	// Rewrite incoming Host Header to server name of the server to which the request is proxied. Enabling this feature rewrites Host Header for requests to all servers in the pool. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	RewriteHostHeaderToServerName bool `json:"rewrite_host_header_to_server_name,omitempty"`
	// If SNI server name is specified, rewrite incoming host header to the SNI server name. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	RewriteHostHeaderToSni bool `json:"rewrite_host_header_to_sni,omitempty"`
	// Enable to do routing when this pool is selected to send traffic. No servers present in routing pool. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	RoutingPool bool `json:"routing_pool,omitempty"`
	// Fully qualified DNS hostname which will be used in the TLS SNI extension in server connections if SNI is enabled. If no value is specified, Avi will use the incoming host header instead. 
	ServerName string `json:"server_name,omitempty"`
	ServerReselect *AlbhttpServerReselect `json:"server_reselect,omitempty"`
	// Server timeout value specifies the time within which a server connection needs to be established and a request-response exchange completes between AVI and the server. Value of 0 results in using default timeout of 60 minutes. Allowed values are 0-21600000. Unit is MILLISECONDS. Default value when not specified in API or module is interpreted by ALB Controller as 0. 
	ServerTimeout int64 `json:"server_timeout,omitempty"`
	// The pool directs load balanced traffic to this list of destination servers. The servers can be configured by IP address, name, network or via IP Address Group. Maximum of 5000 items allowed. 
	Servers []AlbServer `json:"servers,omitempty"`
	// Metadata pertaining to the service provided by this Pool. In Openshift/Kubernetes environments, app metadata info is stored. Any user input to this field will be overwritten by Avi Vantage. 
	ServiceMetadata string `json:"service_metadata,omitempty"`
	// Enable TLS SNI for server connections. If disabled, Avi will not send the SNI extension as part of the handshake. Default value when not specified in API or module is interpreted by ALB Controller as true. 
	SniEnabled bool `json:"sni_enabled,omitempty"`
	// Service Engines will present a client SSL certificate to the server. It is a reference to an object of type SSLKeyAndCertificate. 
	SslKeyAndCertificatePath string `json:"ssl_key_and_certificate_path,omitempty"`
	// When enabled, Avi re-encrypts traffic to the backend servers. The specific SSL profile defines which ciphers and SSL versions will be supported. It is a reference to an object of type SSLProfile. 
	SslProfilePath string `json:"ssl_profile_path,omitempty"`
	// This tier1_lr field should be set same as VirtualService associated for NSX-T. 
	Tier1Path string `json:"tier1_path,omitempty"`
	// Do not translate the client's destination port when sending the connection to the server. The pool or servers specified service port will still be used for health monitoring. Allowed in Basic(Allowed values- false) edition, Essentials(Allowed values- false) edition, Enterprise edition. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	UseServicePort bool `json:"use_service_port,omitempty"`
	// Virtual Routing Context that the pool is bound to. This is used to provide the isolation of the set of networks the pool is attached to. The pool inherits the Virtual Routing Conext of the Virtual Service, and this field is used only internally, and is set by pb-transform. It is a reference to an object of type VrfContext. 
	VrfName string `json:"vrf_name,omitempty"`
}
