/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer PoolServer object
type AlbPoolServer struct {
	// DNS resolvable name of the server. May be used in place of the IP address. 
	Hostname string `json:"hostname,omitempty"`
	Ip *AlbIpAddr `json:"ip"`
	// Port of the pool server listening for HTTP/HTTPS. Default value is the default port in the pool. Allowed values are 1-65535. 
	Port int64 `json:"port,omitempty"`
}
