/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type TnNodeAgentstatus struct {
	// Show the Node Agent connected VM vif status.
	HyperbusConnectionStatus string `json:"hyperbus_connection_status"`
	// Connected VM vif id.
	VifId string `json:"vif_id"`
}
