/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer ClientLogFilter object
type AlbClientLogFilter struct {
	// Placeholder for description of property all_headers of obj type ClientLogFilter field type str  type boolean. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	AllHeaders bool `json:"all_headers,omitempty"`
	ClientIp *AlbIpAddrMatch `json:"client_ip,omitempty"`
	// Special values are 0 - 'infinite'. Unit is MIN. Default value when not specified in API or module is interpreted by ALB Controller as 30. 
	Duration int64 `json:"duration,omitempty"`
	// Placeholder for description of property enabled of obj type ClientLogFilter field type str  type boolean. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	Enabled bool `json:"enabled"`
	// Number of index.
	Index int64 `json:"index"`
	// Name of the object.
	Name string `json:"name"`
	Uri *AlbStringMatch `json:"uri,omitempty"`
}
