/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Related attribute on the target resource for conditional constraints based on related attribute value. Example - destinationGroups/service/action is related attribute of   sourceGroups in communcation entry. 
type RelatedAttribute struct {
	// Related attribute name on the target entity.
	Attribute string `json:"attribute"`
}
