/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// LBAccessListControl is used to define how IP access list control can filter the connections from clients. 
type LbAccessListControl struct {
	// ALLOW means connections matching grouping object IP list are allowed and requests not matching grouping object IP list are dropped. DROP means connections matching grouping object IP list are dropped and requests not matching grouping object IP list are allowed. 
	Action string `json:"action"`
	// The enabled flag indicates whether to enable access list control option. It is false by default. 
	Enabled bool `json:"enabled,omitempty"`
	// The path of grouping object which defines the IP addresses or ranges to match the client IP. 
	GroupPath string `json:"group_path"`
}
