/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer HTTPPolicies object
type AlbhttpPolicies struct {
	// path of the virtual service HTTP policy collection. It is a reference to an object of type HTTPPolicySet. 
	HttpPolicySetPath string `json:"http_policy_set_path"`
	// Index of the virtual service HTTP policy collection.
	Index int64 `json:"index"`
}
