/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Contains type specific properties of generic realized entity
type AttributeVal struct {
	// Datatype of the property
	DataType string `json:"data_type,omitempty"`
	// Attribute key
	Key string `json:"key,omitempty"`
	// If attribute has a single value or collection of values
	Multivalue bool `json:"multivalue,omitempty"`
	// List of attribute values
	Values []string `json:"values,omitempty"`
}
