/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Route map entry
type RouteMapEntry struct {
	// Action for the route map entry 
	Action string `json:"action"`
	// Community list match criteria for route map. Properties community_list_matches and prefix_list_matches are mutually exclusive and cannot be used in the same route map entry. 
	CommunityListMatches []CommunityMatchCriteria `json:"community_list_matches,omitempty"`
	// Prefix list match criteria for route map. Properties community_list_matches and prefix_list_matches are mutually exclusive and cannot be used in the same route map entry. 
	PrefixListMatches []string `json:"prefix_list_matches,omitempty"`
	Set *RouteMapEntrySet `json:"set,omitempty"`
}
