/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer ContentRewriteProfile object
type AlbContentRewriteProfile struct {
	// Enable rewrite on response body. Default value when not specified in API or module is interpreted by ALB Controller as false. 
	ResponseRewriteEnabled bool `json:"response_rewrite_enabled,omitempty"`
	// Rewrite only content types listed in this string group. Content types not present in this list are not rewritten. It is a reference to an object of type StringGroup. 
	RewritableContentPath string `json:"rewritable_content_path,omitempty"`
	// Strings to be matched and replaced with on the response body. This should be configured when response_rewrite_enabled is set to true. 
	RspMatchReplacePair []AlbMatchReplacePair `json:"rsp_match_replace_pair,omitempty"`
}
