/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// A CRL is a time-stamped list identifying revoked certificates.
type X509Crl struct {
	// List of X509CrlEntry.
	CrlEntries []X509CrlEntry `json:"crl_entries,omitempty"`
	// Issuer's distinguished name. (DN)
	Issuer string `json:"issuer,omitempty"`
	// Next update time for the CRL.
	NextUpdate string `json:"next_update,omitempty"`
	// CRL's version number either 1 or 2.
	Version string `json:"version,omitempty"`
}
