/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// IP assignment specification for Static IP List.
type StaticIpListSpec struct {
	ResourceType string `json:"resource_type"`
	// Gateway IP
	DefaultGateway string `json:"default_gateway"`
	// List of IPs for transport node host switch virtual tunnel endpoints
	IpList []string `json:"ip_list"`
	// Subnet mask
	SubnetMask string `json:"subnet_mask"`
}
