/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Organization Unit
type DirectoryOrgUnit struct {
	// List of children Organization Units if any. 
	Children []DirectoryOrgUnit `json:"children"`
	// Distinguished name of the organization unit.
	DistinguishedName string `json:"distinguished_name"`
	// Organization Unit name.
	Name string `json:"name"`
}
