/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer AppCookiePersistenceProfile object
type AlbAppCookiePersistenceProfile struct {
	// Key to use for cookie encryption.
	EncryptionKey string `json:"encryption_key,omitempty"`
	// Header or cookie name for application cookie persistence.
	PrstHdrName string `json:"prst_hdr_name"`
	// The length of time after a client's connections have closed before expiring the client's persistence to a server. Allowed values are 1-720. Unit is MIN. Default value when not specified in API or module is interpreted by ALB Controller as 20. 
	Timeout int64 `json:"timeout,omitempty"`
}
