/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer L4RulePortMatch object
type Albl4RulePortMatch struct {
	// Criterion to use for Virtual Service port matching. Enum options - IS_IN, IS_NOT_IN. 
	MatchCriteria string `json:"match_criteria"`
	// Range of TCP/UDP port numbers of the Virtual Service.
	PortRanges []AlbPortRange `json:"port_ranges,omitempty"`
	// Virtual Service's listening port(s). Allowed values are 1-65535. 
	Ports []int64 `json:"ports,omitempty"`
}
