/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// L2VPN Session Transport Tunnel Data uses a peer code which has all the information to create the transport tunnel. 
type L2VpnSessionTransportTunnelData struct {
	// IPv4 Address of local endpoint.
	LocalAddress string `json:"local_address"`
	// IPv4 Address of Peer endpoint on remote site.
	PeerAddress string `json:"peer_address"`
	// Peer code represents a base64 encoded string which has all the configuration for tunnel. E.g local/peer ips and protocol, encryption algorithm, etc. Peer code also contains PSK; be careful when sharing or storing it. 
	PeerCode string `json:"peer_code,omitempty"`
}
