/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Identity Firewall statistics data.
type IdfwSystemStats struct {
	// Number of concurrent logged on users (across VDI & RDSH).  Multiple logins by the same user is counted as 1. 
	NumConcurrentUsers int32 `json:"num_concurrent_users"`
	// Number of active user sessions/logins in IDFW enabled compute collections (including both UP and DOWN hosts).  N sessions/logins by the same user is counted as n. 
	NumUserSessions int32 `json:"num_user_sessions"`
}
