/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Match condition for client certficate issuer DN.
type LbClientCertificateIssuerDnCondition struct {
	// If true, case is significant when comparing issuer DN value. 
	CaseSensitive bool `json:"case_sensitive,omitempty"`
	// Value of issuer DN.
	IssuerDn string `json:"issuer_dn"`
	// Match type of issuer DN.
	MatchType string `json:"match_type,omitempty"`
}
