/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Aggregate of L2Vpn peer config across Enforcement Points. 
type AggregateL2VpnPeerConfig struct {
	// Policy path referencing the L2Vpn. 
	L2vpnPath string `json:"l2vpn_path"`
	// List of L2Vpn peer config per Enforcement Point. 
	L2vpnPeerConfigPerEnforcementPoint []L2VpnPeerConfigPerEnforcementPoint `json:"l2vpn_peer_config_per_enforcement_point,omitempty"`
}
