/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type BgpAddressFamily struct {
	// Count of in prefixes
	InPrefixCount int64 `json:"in_prefix_count,omitempty"`
	// Count of out prefixes
	OutPrefixCount int64 `json:"out_prefix_count,omitempty"`
	// BGP address family type
	Type_ string `json:"type,omitempty"`
}
