/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type SiAggregatedDataCounterEx struct {
	RxBytes *SiDataCounter `json:"rx_bytes,omitempty"`
	RxPackets *SiDataCounter `json:"rx_packets,omitempty"`
	TxBytes *SiDataCounter `json:"tx_bytes,omitempty"`
	TxPackets *SiDataCounter `json:"tx_packets,omitempty"`
	DroppedBySecurityPackets *SiPacketsDroppedBySecurity `json:"dropped_by_security_packets,omitempty"`
	MacLearning *SiMacLearningCounters `json:"mac_learning,omitempty"`
}
