/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// ID and status of the VM on Identity Firewall compute collection. 
type IdfwVirtualMachineStatus struct {
	// VM ID of the VM on Identity Firewall compute collection. 
	VmId string `json:"vm_id"`
	// Status of the Identity Firewall compute collection's Virtual Machine. 
	VmStatus []IdfwVirtualMachineCondition `json:"vm_status"`
}
