/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// compute collection ID and status connected to VC.
type IdfwComputeCollectionStatus struct {
	// IDFW compute collection ID connected to VC.
	ComputeCollectionId string `json:"compute_collection_id"`
	// IDFW enabled compute collection status.
	ComputeCollectionStatus []IdfwComputeCollectionCondition `json:"compute_collection_status,omitempty"`
}
