/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// time range filter information
type TimeRangeFilterInfo struct {
	// from parameter name used for time range filter from date value.
	FromParamName string `json:"from_param_name,omitempty"`
	// to parameter name used for time range filter to date value.
	ToParamName string `json:"to_param_name,omitempty"`
	// type of time range filter value can be epoch, ISO date Format.
	ValueType string `json:"value_type,omitempty"`
}
