/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// The key is used to specify the symmetric key which is used to verify the signature of JWT tokens. 
type LbJwtSymmetricKey struct {
	// The property is used to identify JWT key type. 
	Type_ string `json:"type"`
}
