/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// CPU usage of DPDK and non-DPDK cores
type CpuUsage struct {
	// Indicates the average usage of all DPDK cores in percentage.
	AvgCpuCoreUsageDpdk float32 `json:"avg_cpu_core_usage_dpdk,omitempty"`
	// Indicates the average usage of all non-DPDK cores in percentage.
	AvgCpuCoreUsageNonDpdk float32 `json:"avg_cpu_core_usage_non_dpdk,omitempty"`
	// Indicates the highest CPU utilization value among DPDK cores in percentage.
	HighestCpuCoreUsageDpdk float32 `json:"highest_cpu_core_usage_dpdk,omitempty"`
	// Indicates the highest cpu utilization value among non_dpdk cores in percentage.
	HighestCpuCoreUsageNonDpdk float32 `json:"highest_cpu_core_usage_non_dpdk,omitempty"`
}
