/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer HealthMonitorRadius object
type AlbHealthMonitorRadius struct {
	// Radius monitor will query Radius server with this password.
	Password string `json:"password,omitempty"`
	// Radius monitor will query Radius server with this shared secret. 
	SharedSecret string `json:"shared_secret,omitempty"`
	// Radius monitor will query Radius server with this username.
	Username string `json:"username"`
}
