/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Error along with its metadata
type ErrorResolverMetadata struct {
	// The entity/node UUID where the error has occurred.
	EntityId string `json:"entity_id"`
	// The error id as reported by the entity where the error occurred.
	ErrorId int64 `json:"error_id"`
	SystemMetadata *ErrorResolverSystemMetadata `json:"system_metadata,omitempty"`
	UserMetadata *ErrorResolverUserMetadata `json:"user_metadata,omitempty"`
}
