/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Header of a widget that provides additional information. This will be shown at the container level. It includes details as label value pairs.
type Header struct {
	// If the condition is met then the header will be applied. Examples of expression syntax are provided under 'example_request' section of 'CreateWidgetConfiguration' API.
	Condition string `json:"condition,omitempty"`
	// Alignment of header labels.
	ContentAlignment string `json:"content_alignment,omitempty"`
	// An array of widgets which will appear inside the container header Instead of 'sub_headers' property use this property.
	SubHeaderWidgets []WidgetItem `json:"sub_header_widgets,omitempty"`
	// An array of label-value properties. This field is deprecated instead used 'sub_header_widgets' property to define header widgets.
	SubHeaders []PropertyItem `json:"sub_headers,omitempty"`
}
