/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer HTTPSecurityActionRateProfile object
type AlbhttpSecurityActionRateProfile struct {
	Action *AlbRateLimiterAction `json:"action"`
	// Rate limiting should be done on a per client ip basis.
	PerClientIp bool `json:"per_client_ip,omitempty"`
	// Rate limiting should be done on a per request uri path basis. 
	PerUriPath bool `json:"per_uri_path,omitempty"`
	RateLimiter *AlbRateLimiter `json:"rate_limiter"`
}
