/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type LogicalRouterStatusPerNode struct {
	// Only populated by Policy APIs
	EdgePath string `json:"edge_path,omitempty"`
	// A service router's HA status on an edge node
	HighAvailabilityStatus string `json:"high_availability_status"`
	// id of the service router where the router status is retrieved.
	ServiceRouterId string `json:"service_router_id,omitempty"`
	// This field is populated for sateful active-active mode. Runtime state is only synced among nodes in the same sub cluster. 
	SubClusterId string `json:"sub_cluster_id,omitempty"`
	// id of the transport node where the router status is retrieved.
	TransportNodeId string `json:"transport_node_id"`
}
