/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Each revoked certificate is identified in a CRL by its certificate serial number.
type X509CrlEntry struct {
	// Revocation date.
	RevocationDate string `json:"revocation_date,omitempty"`
	// The revoked certificate's serial number.
	SerialNumber string `json:"serial_number,omitempty"`
}
