/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// An entity that holds the list of IDS signatures attached to an IDS Profile depending upon the Profile's criteria. These are the Signatures which needs to be detected. 
type IdsProfileSignatures struct {
	// Represents the Path of the IDS Profile. 
	ProfilePath string `json:"profile_path,omitempty"`
	// List of IDS signature ids which need to be detected.
	Signatures []string `json:"signatures,omitempty"`
}
