/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Supported Attribute Keys are APP_ID, URL_CATEGORY, URL_REPUTATION, CUSTOM_URL 
type L7AccessAttributes struct {
	// Source of attribute value i.e whether system defined or custom value
	AttributeSource string `json:"attribute_source,omitempty"`
	// Datatype for attribute
	Datatype string `json:"datatype"`
	// Description for attribute value
	Description string `json:"description,omitempty"`
	// Describes whether the APP_ID value is ALG type or not.
	IsALGType bool `json:"isALGType,omitempty"`
	// URL_Reputation is currently not available. Please do not use it in Attribute Key while creating context profile
	Key string `json:"key"`
	// This is optional part that can hold additional data about the attribute key/values. Example - For URL CATEGORY key , it specified super category for url category value. This is generic array and can hold multiple meta information about key/values in future 
	Metadata []ContextProfileAttributesMetadata `json:"metadata,omitempty"`
	// Reference to sub attributes for the attribute
	SubAttributes []PolicySubAttributes `json:"sub_attributes,omitempty"`
	// Multiple attribute values can be specified as elements of array. 
	Value []string `json:"value"`
}
