/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type PacketNumberSampling struct {
	// Sampling type
	SamplingType string `json:"sampling_type"`
	// 1 out of how many packets is sampled
	SamplingRate int64 `json:"sampling_rate"`
}
