/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Properties of the layout of a container or widget
type LayoutProperties struct {
	// Describes the number of columns of grid layout of a container or widget. This property is applicable for grid layout only.
	NumColumns int32 `json:"num_columns,omitempty"`
	// Describes the number of rows of grid layout of a container or widget. This property is applicable for grid layout only.
	NumRows int32 `json:"num_rows,omitempty"`
}
