/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer SSLProfileSelector object
type AlbsslProfileSelector struct {
	ClientIpList *AlbIpAddrMatch `json:"client_ip_list"`
	// SSL profile for the client IP addresses listed. It is a reference to an object of type SSLProfile. 
	SslProfilePath string `json:"ssl_profile_path"`
}
