/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Antrea Controller status, including component status, connected agent and CONTROLLER_ prefix conditions status.
type AntreaControllerStatus struct {
	// Collection of controller related conditions. 
	Conditions []ComponentConditionItem `json:"conditions,omitempty"`
	// If status is UNKNOWN, this number is meaningless. 
	ConnectedAgentNum int32 `json:"connected_agent_num,omitempty"`
	// Indicate overall healthy status. 
	Status string `json:"status,omitempty"`
}
