/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Query statistics counters of used cache from node 
type NsxTPerNodeUsedCacheStatistics struct {
	// The total number of cached entries
	CachedEntries int64 `json:"cached_entries,omitempty"`
	// UUID of active/standby transport node
	NodeId string `json:"node_id,omitempty"`
	// The memory size used in cache, in kb
	UsedCacheSize int64 `json:"used_cache_size,omitempty"`
}
