/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Contains info used to configure the VM on deployment.
type AlbControllerNodeVmDeploymentConfig struct {
	// Specifies the config for the platform through which to deploy the VM. 
	PlacementType string `json:"placement_type"`
}
