/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Next hop configuration for network
type RouterNexthop struct {
	// Cost associated with next hop route
	AdminDistance int32 `json:"admin_distance,omitempty"`
	// Next hop gateway IP address
	IpAddress string `json:"ip_address,omitempty"`
	// Interface path associated with current route. For example: specify a policy path referencing the IPSec VPN Session. 
	Scope []string `json:"scope,omitempty"`
}
