/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Tier0 stateful services config to define stateful
type Tier0StatefulServicesConfig struct {
	// This is used to enable or disable ACTIVE-ACTIVE stateful services. 
	Enabled bool `json:"enabled,omitempty"`
	// Redirection policy enum types for enaling stateful services IP_HASH: Hash Source IP or destination ip to redirect packet for load sharing and stateful services. NONE: Disable redirection. It requires user to define static traffic group per edge node and expects external router to forward return packet back to the same edge node. 
	RedirectionPolicy string `json:"redirection_policy,omitempty"`
}
