/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer SidebandProfile object
type AlbSidebandProfile struct {
	// IP Address of the sideband server.
	Ip []AlbIpAddr `json:"ip,omitempty"`
	// Maximum size of the request body that will be sent on the sideband. Allowed values are 0-16384. Unit is BYTES. Default value when not specified in API or module is interpreted by ALB Controller as 1024. 
	SidebandMaxRequestBodySize int64 `json:"sideband_max_request_body_size,omitempty"`
}
