/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Set Fields is an action to set fields of the source event. 
type SetFields struct {
	// Reaction Action resource type. 
	ResourceType string `json:"resource_type"`
	// Field Settings.
	FieldSettings []FieldSetting `json:"field_settings,omitempty"`
}
