/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer RoleFilterMatchLabel object
type AlbRoleFilterMatchLabel struct {
	// Key for filter match.
	Key string `json:"key"`
	// Values for filter match. Multiple values will be evaluated as OR. Example  key = value1 OR key = value2. Behavior for match is key = (STAR) if this field is empty. 
	Values []string `json:"values,omitempty"`
}
