/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Answer of nslookup
type NsxTDnsQueryAnswer struct {
	// Resolved IP address matched with the nslookup address provided as a request parameter. 
	Address string `json:"address,omitempty"`
	// Matched name of the given address. 
	Name string `json:"name,omitempty"`
}
