/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Recommended Feature Permission
type RecommendedFeaturePermission struct {
	// Permission
	RecommendedPermissions []string `json:"recommended_permissions"`
	// List of source features
	SrcFeatures []string `json:"src_features"`
	// Feature
	TargetFeature string `json:"target_feature"`
}
