/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type LiveTraceFilterInvalidInfo struct {
	Filter *LiveTraceFilterData `json:"filter,omitempty"`
	// The description of why the filter is rejected by the transport node.
	Reason string `json:"reason,omitempty"`
}
