/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type TransportInfo struct {
	// Destination port
	DstPort int64 `json:"dst_port,omitempty"`
	// Protocol type over IP layer
	Protocol string `json:"protocol,omitempty"`
	// Source port
	SrcPort int64 `json:"src_port,omitempty"`
}
