/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Ip header stuffs for Antrea traceflow. 
type AntreaTraceflowIpHeader struct {
	// Destination ip address in IpHeader. 
	DstIp string `json:"dstIp,omitempty"`
	// Protocol setting in IpHeader. 
	Flags int64 `json:"flags,omitempty"`
	// Protocol setting in IpHeader. 
	Protocol int64 `json:"protocol,omitempty"`
	// Source ip address in IpHeader. 
	SrcIp string `json:"srcIp,omitempty"`
	// TTL value in IpHeader. Default is 64. 
	Ttl int64 `json:"ttl,omitempty"`
}
