/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Injection holding a key and a corresponding value. 
type Injection struct {
	// Injection key.
	Key string `json:"key"`
	Value *InjectionValue `json:"value"`
}
