/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer HTTPLocalFile object
type AlbhttpLocalFile struct {
	// Mime-type of the content in the file.
	ContentType string `json:"content_type"`
	// File content to used in the local HTTP response body.
	FileContent string `json:"file_content"`
}
