/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer IpAddrPrefix object
type AlbIpAddrPrefix struct {
	IpAddr *AlbIpAddr `json:"ip_addr"`
	// Number of mask.
	Mask int64 `json:"mask"`
}
