/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Consolidated Realized Status Per Enforcement Point. 
type BaseConsolidatedStatusPerEnforcementPoint struct {
	Alarm *PolicyRuntimeAlarm `json:"alarm,omitempty"`
	// Policy Path referencing the enforcement point where the info is fetched. 
	EnforcementPointPath string `json:"enforcement_point_path,omitempty"`
	ConsolidatedStatus *ConsolidatedStatus `json:"consolidated_status,omitempty"`
	// Enforcement Point Id.
	EnforcementPointId string `json:"enforcement_point_id,omitempty"`
	ResourceType string `json:"resource_type"`
	// The site where this enforcement point resides.
	SitePath string `json:"site_path,omitempty"`
}
