/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Set criteria for route map entry
type RouteMapEntrySet struct {
	// AS path prepend to influence route selection. 
	AsPathPrepend string `json:"as_path_prepend,omitempty"`
	// Set BGP regular or large community for matching routes. A maximum of one value for each community type separated by space. Well-known community name, community value in aa:nn (2byte:2byte) format for regular community and community value in aa:bb:nn (4byte:4byte:4byte) format for large community are supported. 
	Community string `json:"community,omitempty"`
	// Local preference indicates the degree of preference for one BGP route over other BGP routes. The path with highest local preference is preferred. 
	LocalPreference int64 `json:"local_preference,omitempty"`
	// Multi exit descriminator (MED) is a hint to BGP neighbors about the preferred path into an autonomous system (AS) that has multiple entry points. A lower MED value is preferred over a higher value. 
	Med int32 `json:"med,omitempty"`
	// For incoming and import route_maps on receiving both v6 global and v6 link-local address for the route, prefer to use the global address as the next hop. By default, it prefers the link-local next hop. 
	PreferGlobalV6NextHop bool `json:"prefer_global_v6_next_hop,omitempty"`
	// Weight is used to select a route when multiple routes are available to the same network. Route with the highest weight is preferred. 
	Weight int32 `json:"weight,omitempty"`
}
