/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer SSLKeyParams object
type AlbsslKeyParams struct {
	// Enum options - SSL_KEY_ALGORITHM_RSA, SSL_KEY_ALGORITHM_EC. Default value when not specified in API or module is interpreted by ALB Controller as SSL_KEY_ALGORITHM_RSA. 
	Algorithm string `json:"algorithm"`
	EcParams *AlbsslKeyEcParams `json:"ec_params,omitempty"`
	RsaParams *AlbsslKeyRsaParams `json:"rsa_params,omitempty"`
}
