/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Contains dupliacte IP detection related discovery options.
type DuplicateIpDetectionOptions struct {
	// Indicates whether duplicate IP detection should be enabled
	DuplicateIpDetectionEnabled bool `json:"duplicate_ip_detection_enabled,omitempty"`
}
