/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced load balancer HTTPResponseRule object
type AlbhttpResponseRule struct {
	// Log all HTTP headers upon rule match.
	AllHeaders bool `json:"all_headers,omitempty"`
	// Enable or disable the rule. Default value when not specified in API or module is interpreted by ALB Controller as true. 
	Enable bool `json:"enable"`
	// HTTP header rewrite action.
	HdrAction []AlbhttpHdrAction `json:"hdr_action,omitempty"`
	// Index of the rule.
	Index int64 `json:"index"`
	LocHdrAction *AlbhttpRewriteLocHdrAction `json:"loc_hdr_action,omitempty"`
	// Log HTTP request upon rule match.
	Log bool `json:"log,omitempty"`
	Match *AlbResponseMatchTarget `json:"match,omitempty"`
	// Name of the rule.
	Name string `json:"name"`
}
