/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type VmToolsInfo struct {
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	Self *SelfResourceLink `json:"_self,omitempty"`
	// Timestamp of last modification
	LastSyncTime int64 `json:"_last_sync_time,omitempty"`
	// Description of this resource
	Description string `json:"description,omitempty"`
	// Defaults to ID if not set
	DisplayName string `json:"display_name,omitempty"`
	// The type of this resource.
	ResourceType string `json:"resource_type"`
	// Specifies list of scope of discovered resource. e.g. if VHC path is associated with principal identity, who owns the discovered resource, then scope id will be VHC path and scope type will be VHC. 
	Scope []DiscoveredResourceScope `json:"scope,omitempty"`
	// Opaque identifiers meaningful to the API user
	Tags []Tag `json:"tags,omitempty"`
	// Current external id of this virtual machine in the system.
	ExternalId string `json:"external_id,omitempty"`
	// Version of file agent on the VM of a third party partner solution.
	FileAgentVersion string `json:"file_agent_version,omitempty"`
	// Id of the VM which is assigned locally by the host. It is the VM-moref on ESXi hosts, in other environments it is VM UUID.
	HostLocalId string `json:"host_local_id,omitempty"`
	// Version of network agent on the VM of a third party partner solution.
	NetworkAgentVersion string `json:"network_agent_version,omitempty"`
	Source *ResourceReference `json:"source,omitempty"`
	// Connectivity Status between each Guest Introspection Solution deployed in the data center with the guest VM.
	SvmStatus []SvmConnectivityStatus `json:"svmStatus,omitempty"`
	// Endpoint Protection (Third party AV partner using NXGI) status on the VM. TRUE  - VM is configured and protected by EPP Service VM. FALSE - VM is either not configured for protection or VM is disconnected from EPP Service VM.
	SvmConnectivity bool `json:"svm_connectivity,omitempty"`
	// Version of VMTools installed on the VM.
	ToolsVersion string `json:"tools_version,omitempty"`
	// Type of VM - Edge, Service or other.
	VmType string `json:"vm_type,omitempty"`
}
