/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Advanced Load Balancer controller cluster information about nodes in the cluster and cluster information.
type AlbControllerClusterInfo struct {
	// Advanced Load Balancer controller cluster name.
	ClusterName string `json:"cluster_name,omitempty"`
	// Advanced Load Balancer controller cluster state.
	ClusterState string `json:"cluster_state,omitempty"`
	// ID of the Cluster maintained internally. Note: This is automatically generated and cannot be modified. 
	ClusterUuid string `json:"cluster_uuid,omitempty"`
	Error_ *AlbControllerClusterRuntimeError `json:"error,omitempty"`
	// Advanced Load Balancer controller node information
	Nodes []AlbControllerNodeInfo `json:"nodes,omitempty"`
	// Advanced Load Balancer cluster state not STABLE reason.
	Reason string `json:"reason,omitempty"`
	// Advanced Load Balancer controller cluster version.
	Version string `json:"version,omitempty"`
	// Advanced Load Balancer controller cluster virtual_ip. 
	VirtualIp string `json:"virtual_ip,omitempty"`
}
