/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Key Store information about the url alias or datasource.
type KeyStoreInfo struct {
	// A location of the keystor file which stores private key and identity certificates that will be presented to both parties (server or client) for verification.
	Keystore string `json:"keystore,omitempty"`
	// Its an alias specified when an entity is added to the keystore.
	KeystoreAlias string `json:"keystore_alias,omitempty"`
	// A location of the key store pass phrase file.
	KeystorePhrase string `json:"keystore_phrase,omitempty"`
	// A location of the trust store file which stores the certificate from CA that verify the certificate presented by the server in SSL connection.
	Truststore string `json:"truststore,omitempty"`
}
