/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type PolicyCapacityDashboardUsage struct {
	// Indicate the current usage count of object type. 
	CurrentUsageCount int64 `json:"current_usage_count"`
	// Current usage percentage for object type 
	CurrentUsagePercentage float32 `json:"current_usage_percentage"`
	// Display name for NSX object type. 
	DisplayName string `json:"display_name"`
	// This is the maximum supported count for object type in consideration. 
	MaxSupportedCount int64 `json:"max_supported_count"`
	// Indicate the object type for which usage is calculated. 
	UsageType string `json:"usage_type"`
}
