/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Current backup operation status
type CurrentBackupOperationStatus struct {
	// Unique identifier of current backup
	BackupId string `json:"backup_id,omitempty"`
	// Current step of operation
	CurrentStep string `json:"current_step,omitempty"`
	// Additional human-readable status information about current step
	CurrentStepMessage string `json:"current_step_message,omitempty"`
	// Time when operation is expected to end
	EndTime int64 `json:"end_time,omitempty"`
	// Type of operation that is in progress. Returns none if no operation is in progress, in which case none of the other fields will be set. 
	OperationType string `json:"operation_type,omitempty"`
	// Time when operation was started
	StartTime int64 `json:"start_time,omitempty"`
}
