/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Field Setting Value. 
type FieldSettingValue struct {
	// Field Setting Value resource type. 
	ResourceType string `json:"resource_type"`
}
