/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Dropdown Filter plotting configuration.
type DropdownFilterPlotConfiguration struct {
	// Allow maximize capability for this widget
	AllowMaximize bool `json:"allow_maximize,omitempty"`
	// If the condition is met then the given chart config is applied to the widget configuration.
	Condition string `json:"condition,omitempty"`
	// Allow search on drop down filter. 
	AllowSearch bool `json:"allow_search,omitempty"`
}
