/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type RaConfig struct {
	// The maximum number of hops through which packets can pass before being discarded. 
	HopLimit int64 `json:"hop_limit,omitempty"`
	// The time interval in seconds, in which the prefix is advertised as valid. 
	PrefixLifetime int64 `json:"prefix_lifetime,omitempty"`
	// The time interval in seconds, in which the prefix is advertised as preferred. 
	PrefixPreferredTime int64 `json:"prefix_preferred_time,omitempty"`
	// Interval between 2 Router advertisement in seconds. 
	RaInterval int64 `json:"ra_interval,omitempty"`
	// Router lifetime value in seconds. A value of 0 indicates the router is not a default router for the receiving end. Any other value in this field specifies the lifetime, in seconds, associated with this router as a default router. 
	RouterLifetime int64 `json:"router_lifetime,omitempty"`
	// NDRA Router preference value with MEDIUM as default. If the router_lifetime is 0, the preference must be set to MEDIUM. 
	RouterPreference string `json:"router_preference,omitempty"`
}
