/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// configuration parameters for Bridge Profile
type BridgeProfileConfig struct {
	// Same bridge profile can be configured on different segments. Each bridge profile on a segment must unique.
	BridgeProfilePath string `json:"bridge_profile_path"`
	// The name of the switching uplink teaming policy for the bridge endpoint. This name corresponds to one fot he switching uplink teaming policy names listed in teh transport zone. When this property is not specified, the teaming policy is assigned by MP.
	UplinkTeamingPolicyName string `json:"uplink_teaming_policy_name,omitempty"`
	// VLAN specification for bridge endpoint. Either VLAN ID or VLAN ranges can be specified. Not both.
	VlanIds []string `json:"vlan_ids,omitempty"`
	// VLAN transport zone should belong to the enforcment-point as the transport zone specified in the segment.
	VlanTransportZonePath string `json:"vlan_transport_zone_path"`
}
