/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Schedule to specify the interval time at which automated backups need to be taken
type IntervalBackupSchedule struct {
	// Schedule type
	ResourceType string `json:"resource_type"`
	// Time interval in seconds between two consecutive automated backups
	SecondsBetweenBackups int64 `json:"seconds_between_backups,omitempty"`
}
