/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// OSPF summary link state details.
type MpOspfSummaryLinkStates struct {
	// OSPF advertised router
	AdvertisedRouter string `json:"advertised_router,omitempty"`
	// Cost of the route
	Checksum string `json:"checksum,omitempty"`
	// OSPF link id
	LinkStateId string `json:"link_state_id,omitempty"`
	// Sequence number
	SequenceNumber string `json:"sequence_number,omitempty"`
	// OSPF summary address
	SummaryAddress string `json:"summary_address,omitempty"`
	// LSA age
	UpTime int64 `json:"up_time,omitempty"`
}
