/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Node status properties
type NodeStatusProperties struct {
	// The server will populate this field when returing the resource. Ignored on PUT and POST.
	Links []ResourceLink `json:"_links,omitempty"`
	// Schema for this resource
	Schema string `json:"_schema,omitempty"`
	Self *SelfResourceLink `json:"_self,omitempty"`
	// Number of CPU cores on the system
	CpuCores int64 `json:"cpu_cores,omitempty"`
	CpuUsage *CpuUsage `json:"cpu_usage,omitempty"`
	// Amount of disk space available on the system, in kilobytes.
	DiskSpaceTotal int64 `json:"disk_space_total,omitempty"`
	// Amount of disk space in use on the system, in kilobytes
	DiskSpaceUsed int64 `json:"disk_space_used,omitempty"`
	// Number of DPDK cores on Edge Node which are used for packet IO processing.
	DpdkCpuCores int64 `json:"dpdk_cpu_cores,omitempty"`
	EdgeMemUsage *EdgeTransportNodeMemoryUsage `json:"edge_mem_usage,omitempty"`
	// File systems configured on the system
	FileSystems []NodeFileSystemProperties `json:"file_systems,omitempty"`
	// Host name of the system
	Hostname string `json:"hostname,omitempty"`
	// One, five, and fifteen minute load averages for the system
	LoadAverage []float32 `json:"load_average,omitempty"`
	// Amount of RAM on the system that can be flushed out to disk, in kilobytes
	MemCache int64 `json:"mem_cache,omitempty"`
	// Amount of RAM allocated to the system, in kilobytes
	MemTotal int64 `json:"mem_total,omitempty"`
	// Amount of RAM in use on the system, in kilobytes
	MemUsed int64 `json:"mem_used,omitempty"`
	// Number of non-DPDK cores on Edge Node.
	NonDpdkCpuCores int64 `json:"non_dpdk_cpu_cores,omitempty"`
	// Source of status data.
	Source string `json:"source,omitempty"`
	// Amount of disk available for swap, in kilobytes
	SwapTotal int64 `json:"swap_total,omitempty"`
	// Amount of swap disk in use, in kilobytes
	SwapUsed int64 `json:"swap_used,omitempty"`
	// Current time expressed in milliseconds since epoch
	SystemTime int64 `json:"system_time,omitempty"`
	// Milliseconds since system start
	Uptime int64 `json:"uptime,omitempty"`
}
