/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// Client SSL profile binding. LBClientSslProfileBinding is deprecated as NSX-T Load Balancer is deprecated. 
type LbClientSslProfileBinding struct {
	// Authentication depth is used to set the verification depth in the client certificates chain. 
	CertificateChainDepth int64 `json:"certificate_chain_depth,omitempty"`
	// Client authentication mode.
	ClientAuth string `json:"client_auth,omitempty"`
	// If client auth type is REQUIRED, client certificate must be signed by one of the trusted Certificate Authorities (CAs), also referred to as root CAs, whose self signed certificates are specified. 
	ClientAuthCaPaths []string `json:"client_auth_ca_paths,omitempty"`
	// A Certificate Revocation List (CRL) can be specified in the client-side SSL profile binding to disallow compromised client certificates. 
	ClientAuthCrlPaths []string `json:"client_auth_crl_paths,omitempty"`
	// A default certificate should be specified which will be used if the server does not host multiple hostnames on the same IP address or if the client does not support SNI extension. 
	DefaultCertificatePath string `json:"default_certificate_path"`
	// Client-side SSL profile binding allows multiple certificates, for different hostnames, to be bound to the same virtual server. 
	SniCertificatePaths []string `json:"sni_certificate_paths,omitempty"`
	// Client SSL profile defines reusable, application-independent client side SSL properties. 
	SslProfilePath string `json:"ssl_profile_path,omitempty"`
}
