/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// BGP route details.
type RouteDetails struct {
	// BGP AS path attribute.
	AsPath string `json:"as_path,omitempty"`
	// BGP Local Preference attribute.
	LocalPref int64 `json:"local_pref,omitempty"`
	// BGP Multi Exit Discriminator attribute.
	Med int64 `json:"med,omitempty"`
	// CIDR network address.
	Network string `json:"network,omitempty"`
	// Next hop IP address.
	NextHop string `json:"next_hop,omitempty"`
	// BGP Weight attribute.
	Weight int64 `json:"weight,omitempty"`
}
