/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

// List of VMs on which a particular signature was detected with the count. 
type PolicyIdsVmStats struct {
	// Number of unique VMs on which a particular signature was detected.
	Count int64 `json:"count,omitempty"`
	// List of VM names  on which intrusions of that particular signature type were detected.
	VmList []string `json:"vm_list,omitempty"`
}
