/*
 * NSX-T Data Center Policy API
 *
 * VMware NSX-T Data Center Policy REST API
 *
 * API version: 3.2.1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package nsxt

type FabricHostNode struct {
	// Id of the compute collection to which discovered node belongs.
	ComputeCollectionId string `json:"compute_collection_id,omitempty"`
	// Discovered IP Addresses of the transport node, version 4 or 6
	DiscoveredIpAddresses []string `json:"discovered_ip_addresses,omitempty"`
	// Id of discovered node which was converted to create this node.
	DiscoveredNodeId string `json:"discovered_node_id,omitempty"`
	// Fully qualified domain name of the transport node
	Fqdn string `json:"fqdn,omitempty"`
	HostCredential *HostNodeLoginCredential `json:"host_credential,omitempty"`
	// IP Addresses of the Node, version 4 or 6. 
	IpAddresses []string `json:"ip_addresses"`
	// Indicates host node's maintenance mode state. The state is ENTERING when a task to put the host in maintenance-mode is in progress. 
	MaintenanceModeState string `json:"maintenance_mode_state,omitempty"`
	// The id of the vCenter server managing the ESXi type HostNode
	ManagedByServer string `json:"managed_by_server,omitempty"`
	// Hypervisor type, for example ESXi or RHEL KVM
	OsType string `json:"os_type"`
	// Version of the hypervisor operating system
	OsVersion string `json:"os_version,omitempty"`
	// Specify an installation folder to install the NSX kernel modules for Windows Server. By default, it is C:\\Program Files\\VMware\\NSX\\.
	WindowsInstallLocation string `json:"windows_install_location,omitempty"`
}
